apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-bot
  namespace: default
  labels:
    app: trading-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading-bot
  template:
    metadata:
      labels:
        app: trading-bot
    spec:
      containers:
      - name: trading-bot
        image: godwinekele/godwins-bot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: trading-bot-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: trading-bot
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30080